"""add curation status and progress tracking tables

Revision ID: 3246589a9115
Revises: e37d7da11b83
Create Date: 2026-09-13 11:25:29.848323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3246589a9115'
down_revision: Union[str, Sequence[str], None] = 'e37d7da11b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streaks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('current_streak_days', sa.Integer(), nullable=False),
    sa.Column('longest_streak_days', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('vocabulary_mastery', sa.Float(), nullable=False),
    sa.Column('grammar_mastery', sa.Float(), nullable=False),
    sa.Column('listening_mastery', sa.Float(), nullable=False),
    sa.Column('recall_mastery', sa.Float(), nullable=False),
    sa.Column('completion_pct', sa.Float(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_id', name='uq_progress_lesson')
    )
    op.create_table('attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('vocabulary_id', sa.Uuid(), nullable=True),
    sa.Column('grammar_point_id', sa.Uuid(), nullable=True),
    sa.Column('practice_mode', sa.Enum('RECOGNITION', 'RECALL_EN_TO_KO', 'RECALL_KO_TO_EN', 'LISTENING', 'CONTEXT', name='practicemode'), nullable=True),
    sa.Column('submitted_answer', sa.Text(), nullable=False),
    sa.Column('normalized_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['grammar_point_id'], ['grammar_points.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grammar_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('grammar_point_id', sa.Uuid(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('NEEDS_REVIEW', 'LEARNING', 'MASTERED', name='masterystatus'), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grammar_point_id'], ['grammar_points.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'grammar_point_id', name='uq_grammar_progress')
    )
    op.create_table('vocabulary_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('vocabulary_id', sa.Uuid(), nullable=False),
    sa.Column('practice_mode', sa.Enum('RECOGNITION', 'RECALL_EN_TO_KO', 'RECALL_KO_TO_EN', 'LISTENING', 'CONTEXT', name='practicemode'), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('NEEDS_REVIEW', 'LEARNING', 'MASTERED', name='masterystatus'), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'vocabulary_id', 'practice_mode', name='uq_vocab_progress_mode')
    )
    op.create_table('mistakes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('VOCABULARY_RECALL', 'GRAMMAR_CONCEPT', 'SPELLING', 'SPACING', 'SENTENCE_ORDER', 'COMPREHENSION', 'LISTENING', 'PRONUNCIATION', 'RECOGNITION', 'APPLICATION', name='mistakecategory'), nullable=False),
    sa.Column('vocabulary_id', sa.Uuid(), nullable=True),
    sa.Column('grammar_point_id', sa.Uuid(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['grammar_point_id'], ['grammar_points.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    curation_status_enum = postgresql.ENUM(
        'DRAFT', 'NEEDS_REVIEW', 'REJECTED', 'HUMAN_APPROVED', 'CANONICAL', name='curationstatus'
    )
    curation_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('activities', sa.Column('curation_status', curation_status_enum, nullable=False))
    op.add_column('activities', sa.Column('proposed_by', sa.String(length=128), nullable=True))
    op.add_column('activities', sa.Column('reviewed_by', sa.String(length=128), nullable=True))
    op.add_column('activities', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('activities', 'verification_status')
    op.add_column('grammar_points', sa.Column('curation_status', curation_status_enum, nullable=False))
    op.add_column('grammar_points', sa.Column('proposed_by', sa.String(length=128), nullable=True))
    op.add_column('grammar_points', sa.Column('reviewed_by', sa.String(length=128), nullable=True))
    op.add_column('grammar_points', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('grammar_points', 'verification_status')
    op.add_column('vocabulary', sa.Column('curation_status', curation_status_enum, nullable=False))
    op.add_column('vocabulary', sa.Column('proposed_by', sa.String(length=128), nullable=True))
    op.add_column('vocabulary', sa.Column('reviewed_by', sa.String(length=128), nullable=True))
    op.add_column('vocabulary', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('vocabulary', 'verification_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocabulary', sa.Column('verification_status', postgresql.ENUM('PENDING', 'APPROVED', 'EDITED', 'REJECTED', 'NEEDS_REVIEW', name='verificationstatus'), autoincrement=False, nullable=False))
    op.drop_column('vocabulary', 'reviewed_at')
    op.drop_column('vocabulary', 'reviewed_by')
    op.drop_column('vocabulary', 'proposed_by')
    op.drop_column('vocabulary', 'curation_status')
    op.add_column('grammar_points', sa.Column('verification_status', postgresql.ENUM('PENDING', 'APPROVED', 'EDITED', 'REJECTED', 'NEEDS_REVIEW', name='verificationstatus'), autoincrement=False, nullable=False))
    op.drop_column('grammar_points', 'reviewed_at')
    op.drop_column('grammar_points', 'reviewed_by')
    op.drop_column('grammar_points', 'proposed_by')
    op.drop_column('grammar_points', 'curation_status')
    op.add_column('activities', sa.Column('verification_status', postgresql.ENUM('PENDING', 'APPROVED', 'EDITED', 'REJECTED', 'NEEDS_REVIEW', name='verificationstatus'), autoincrement=False, nullable=False))
    op.drop_column('activities', 'reviewed_at')
    op.drop_column('activities', 'reviewed_by')
    op.drop_column('activities', 'proposed_by')
    op.drop_column('activities', 'curation_status')
    postgresql.ENUM(name='curationstatus').drop(op.get_bind(), checkfirst=True)
    op.drop_table('mistakes')
    op.drop_table('vocabulary_progress')
    op.drop_table('grammar_progress')
    op.drop_table('attempts')
    op.drop_table('progress')
    op.drop_table('streaks')
    postgresql.ENUM(name='mistakecategory').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='masterystatus').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='practicemode').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
