"""add vocabulary romanization and make attempt activity_id nullable

Revision ID: cd92a81fdacd
Revises: f605093afae1
Create Date: 2026-09-13 18:29:05.102227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd92a81fdacd'
down_revision: Union[str, Sequence[str], None] = 'f605093afae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attempts', 'activity_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('vocabulary', sa.Column('romanization', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vocabulary', 'romanization')
    op.alter_column('attempts', 'activity_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
