"""add curriculum, activity, and audio asset schema

Revision ID: e37d7da11b83
Revises: b9aca8ace723
Create Date: 2026-09-12 15:47:31.859641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e37d7da11b83'
down_revision: Union[str, Sequence[str], None] = 'b9aca8ace723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.Enum('TEXTBOOK', 'WORKBOOK', 'VOCAB_GRAMMAR', 'ADDITIONAL_ACTIVITIES', name='sourcetype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('units',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=8), nullable=False),
    sa.Column('title_ko', sa.String(length=255), nullable=True),
    sa.Column('title_en', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('lessons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_blocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ocr_engine', sa.String(length=64), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('draft_text', sa.Text(), nullable=False),
    sa.Column('block_type', sa.String(length=64), nullable=True),
    sa.Column('unit_id', sa.Uuid(), nullable=True),
    sa.Column('lesson_id', sa.Uuid(), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'APPROVED', 'EDITED', 'REJECTED', 'NEEDS_REVIEW', name='verificationstatus'), nullable=False),
    sa.Column('verified_text', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.String(length=128), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['content_sources.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('VOCABULARY_RECOGNITION', 'VOCABULARY_RECALL', 'MULTIPLE_CHOICE', 'FILL_BLANK', 'KOREAN_TEXT_INPUT', 'SENTENCE_ORDERING', 'MATCHING', 'TRANSLATION_TO_KOREAN', 'LISTENING', 'READING', 'DIALOGUE_COMPLETION', 'GRAMMAR_PRACTICE', 'WRITING', 'SPEAKING', name='activitytype'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_block_id', sa.Uuid(), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'APPROVED', 'EDITED', 'REJECTED', 'NEEDS_REVIEW', name='verificationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['source_block_id'], ['content_blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grammar_points',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('name_ko', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('explanation_en', sa.Text(), nullable=True),
    sa.Column('source_block_id', sa.Uuid(), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'APPROVED', 'EDITED', 'REJECTED', 'NEEDS_REVIEW', name='verificationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['source_block_id'], ['content_blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocabulary',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('korean', sa.String(length=255), nullable=False),
    sa.Column('english', sa.String(length=255), nullable=False),
    sa.Column('part_of_speech', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_block_id', sa.Uuid(), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'APPROVED', 'EDITED', 'REJECTED', 'NEEDS_REVIEW', name='verificationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['source_block_id'], ['content_blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accepted_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('answer_text', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('TEXTBOOK', 'WORKBOOK', 'VOCAB_GRAMMAR', 'ADDITIONAL_ACTIVITIES', name='sourcetype'), nullable=False),
    sa.Column('source_archive', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('unit_id', sa.Uuid(), nullable=True),
    sa.Column('lesson_id', sa.Uuid(), nullable=True),
    sa.Column('activity_id', sa.Uuid(), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'APPROVED', 'EDITED', 'REJECTED', 'NEEDS_REVIEW', name='verificationstatus'), nullable=False),
    sa.Column('verified_by', sa.String(length=128), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio_assets')
    op.drop_table('activity_options')
    op.drop_table('accepted_answers')
    op.drop_table('vocabulary')
    op.drop_table('grammar_points')
    op.drop_table('activities')
    op.drop_table('content_blocks')
    op.drop_table('lessons')
    op.drop_table('units')
    op.drop_table('content_sources')
    # ### end Alembic commands ###
