"""add image_path to vocabulary and activities

Revision ID: f605093afae1
Revises: 1c885de625a8
Create Date: 2026-09-13 16:12:05.150110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f605093afae1'
down_revision: Union[str, Sequence[str], None] = '1c885de625a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('image_path', sa.String(length=512), nullable=True))
    op.add_column('vocabulary', sa.Column('image_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vocabulary', 'image_path')
    op.drop_column('activities', 'image_path')
    # ### end Alembic commands ###
